### ISSUE TITLE
setting floorp as default web browser is not working

### ISSUE THREAD

**Issue by brokedarius** [SiL3NC3/PortableRegistrator#23]
Hi folks, the scenario here is that I have this portable browser, that firefox fork floorp which I am trying to make default on my windows 10 machine but I was unsuccessful it would not even work for local html docs. 

I tried running the program as admin to no avail. The program shows as registered but nothing seems to be changed. At least from a practical point of view.

**Comment by SiL3NC3** [comment]
I do not expect anything in the log file... because the dialog "successfully finished" appeared.

So in that case, the only should happen is, that the registry entries got written.
You can check that, when you reopen the PortableRegistrator and look at the dropdown below, where the detected portable registrations are listed.

![image](https://github.com/SiL3NC3/PortableRegistrator/assets/694970/938c526c-4f7e-4ab7-9967-be736e81f42f)

If not, indeed something goes wrong...

What is happening, when you double click a link to a URL (like: https://github.com) which is on the desktop?

Also check the setting of you Default Programs...
https://support.microsoft.com/en-us/windows/change-default-programs-in-windows-e5d82cad-17d1-c53b-3505-f10a32e1894d

If you are familiar with reading code and know how the windows registry works, you can look here:
https://github.com/SiL3NC3/PortableRegistrator/blob/master/PortableRegistratorCommon/Helper/RegistryHelper.cs

At this section you should be able to figure out the locations in the registry, where the portable floorp should be appearing after the registration.

Good luck.

**Comment by da3dsoul1** [comment]
It works fine for me. I'm on windows 11 24H2

**Comment by SiL3NC3** [comment]
sweet, nJoY.

-closed-
